### PR TITLE
Zig example

### PR DESCRIPTION
**Pull request by AndresCarignano**
Added a Zig example! Great work

### CODE REVIEW

**Comment by MattiaMontanari** [comment]
@AndresCarignano thank you! I wasn't even aware of ZIG, thanks for the contribution. 
I'd like to add a Github action to my workflow, does this sound reasonable?

```
  Zig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0  # Specify your desired Zig version
      - name: Build and run
        run: |
          zig build
          zig build run
```

I haven't been able to test it on Docker yet, but I wanted to know if you passed and extra flag to the compiler (like `BUILD_MONO` ..)

Thanks!

**Comment by AndresCarignano** [comment]
I used the flags while debugging but It compiles fine without them so I removed them.

I'm using Zig 0.14 so let me check that out first.

**Comment by AndresCarignano** [comment]
Ok, compiles and runs in 0.13.0 which is the latest stable. :+1:

**Comment by MattiaMontanari** [comment]
Great! Merged - Thank you very much for you contribution!

**Pull request merged**
